### ISSUE TITLE
AVPBooter support

### ISSUE THREAD

**Issue by Naville** [hack-different/iBoot-IDA#4] opened 2022-02-10 07:33 UTC
Hi:
IDA 7.7 no longer contains bc695, as shown [here](https://forum.hex-rays.com/viewtopic.php?t=4743)
Commenting out code trying to reference bc695 crashes [here](https://github.com/hack-different/iBoot-IDA/blob/0570672a7933781666efc00c74da87bcd6c85f05/src/ibootloader/loader.py#L54)
due to loader is not defined if neither condition is met, which is true if the executable is a AVPBooter

**Comment by Naville** [comment] 2022-02-10 07:34
The exact string in ver_str is ``AVPBooter for vmapple2, Copyright 2007-2021, Apple Inc.``

**Comment by Naville** [comment] 2022-02-10 07:36
Unfortunately I can't upload DMCA-ed binaries here.  
The exact location of such AVPBooter is ``/System/Library/Frameworks/Virtualization.framework/Versions/A/Resources/AVPBooter.vmapple2.bin``, on a Apple Silicon Mac

**Comment by cxnder** [comment] 2022-02-14 05:09
I'll have a 7.7 License sometime this week and will take a look at compatibility issues then

**Comment by Naville** [comment] 2022-02-14 05:22
@cxnder No need to. Just stop using bc695 and we're all good here

**Comment by Naville** [comment] 2022-02-14 05:25
@cxnder From what I read on the hex-rays forum [sauce](https://forum.hex-rays.com/viewtopic.php?t=4743), copying over old bc695 would do. 
So I assume the best solution here would be just integrate that module into this project

**Comment by cxnder** [comment] 2022-02-14 05:34
> Commenting out code trying to reference bc695 crashed here

The line referenced makes no sense in terms of a crash;

It seems to be an unused import, so i'm just going to wait till i can actually verify it works fine. 

As for AVPBooter, i'm entirely unfamiliar with what it even is, and i'll need help from someone knowledgeable if support is to be added for it.

**Comment by Naville** [comment] 2022-02-14 05:46
@cxnder 
> It seems to be an unused import
True, but merely an unguarded import (as in no ``try...except...``) is a fatal failure if that module doesn't exists, which in turn broke iBoot-IDA.

> As for AVPBooter, i'm entirely unfamiliar with what it even is

The one I have at hand is used to boot vmapple, you can find a reference implementation [here](https://github.com/matteyeux/ida-iboot-loader) Whether it's work correctly is beyond me though considering I'm new to reversing iBoot too

**Comment by Naville** [comment] 2022-02-14 05:51
Ah I see the confusion here. What I meant is two completely unrelated crashes.
The first one is proofing that we're crashing at bc695, the second one is for missing AVPBooter

**Comment by cxnder** [comment] 2022-02-14 06:15
Unsure if you're the person who just messaged me on discord, so i'll paste this screenshot here. 

Most recent two commits should fix the bcm crash and add bare-minimum support for loading in AVPBooter. It's very late at night here, i'll work on it later this week. 

As for the process of loading it in, see below:

![image](https://user-images.githubusercontent.com/55725881/153809985-d212f89e-1b82-4e56-9c64-0a4d76fc1f44.png)

**Comment by Naville** [comment] 2022-02-14 06:16
Yes it was me. Thanks a lot!

**Comment by cxnder** [comment] 2022-02-22 17:13
Closing this issue as i've confirmed compatibility with 7.7 myself and AVPBooter support now "exists". I do plan on improving it somewhere down the line.

**Closed by cxnder** 2022-02-22 17:13 UTC
